const translations = {
    en: {
        // Nav & General
        "home": "Home",
        "about": "About",
        "services": "Services",
        "religion": "Religion",
        "education": "Education",
        "donate": "Donate",
        "learnMore": "Learn More",
        "readMore": "Read More",
        "contactUs": "Contact Us",
        "viewDetails": "View Details",
        "submit": "Submit",
        "officeHours": "Office Hours: Mon-Fri, 9am - 5pm",
        "copyrightFooter": "Copyright © 2024 Manitoba Islamic Association. All Rights Reserved.",
        "quickLinksFooter": "Quick Links",
        "contactUsFooter": "Contact Us",
        "aboutMIAFooter": "The Manitoba Islamic Association (MIA) is dedicated to serving the diverse Muslim community in Manitoba through religious guidance, education, social services, and community building.",

        // Index Page
        "welcomeTitle": "Welcome to the Manitoba Islamic Association",
        "welcomeSubtitle": "Serving the Muslim community in Manitoba through faith, education, and service.",
        "learnMoreAboutUs": "Learn More About Us",
        "ourServices": "Our Services",
        "prayerTimingsTitle": "Prayer Timings",
        "prayerDate": "May 4, 2025 / 6 Dhū al-Qaʻda 1446",
        "prayer": "Prayer",
        "athan": "Athan",
        "iqamah": "Iqamah",
        "fajr": "Fajr",
        "sunrise": "Sunrise",
        "zuhr": "Zuhr",
        "asr": "Asr",
        "maghrib": "Maghrib",
        "isha": "Isha",
        "jumuahTimings": "Jumuah: 1:45 pm | 3:45 pm",
        "viewMonthlyTimings": "View Monthly Timings",
        "quickLinksTitle": "Quick Links",
        "qlEvents": "Events",
        "qlMiaInstitute": "MIA Institute",
        "qlEducation": "Education",
        "qlFinancialAssistance": "Financial Assistance",
        "qlMiaWakf": "MIA Wakf",
        "qlNewMuslims": "New Muslims",
        "qlMentalHealth": "Mental Health",
        "qlMemberPortal": "Member Portal",
        "qlVolunteer": "Volunteer",
        "qlFuneralServices": "Funeral Services",
        "newsTitle": "Latest News & Announcements",
        "news1Title": "Community Iftar Next Saturday",
        "news1Date": "May 3, 2025",
        "news1Desc": "Join us for a community gathering and break your fast together. All are welcome!",
        "news2Title": "MIA School Enrollment Open",
        "news2Date": "May 1, 2025",
        "news2Desc": "Enrollment for the upcoming academic year at the MIA Institute of Knowledge is now open. Secure your child's place.",
        "news3Title": "Volunteer Call: Eid Festival",
        "news3Date": "April 28, 2025",
        "news3Desc": "We need volunteers to help make our upcoming Eid festival a success. Sign up today!",
        "volunteer": "Volunteer",
        "supportTitle": "Support Your Community Center",
        "supportText": "Your generous donations help us maintain our facilities, run essential programs, and serve the community.",
        "donateNow": "Donate Now",

        // About Page
        "historyTitle": "Our History",
        "historyP1": "The Manitoba Islamic Association (MIA) traces its roots to the late fifties and early sixties of the 20th century, when Muslim immigrants to Manitoba came together to worship, learn and socialize. Founded officially in [Year - Placeholder], MIA has grown from a small group of pioneers into a central organization for the diverse Muslim community in the province.",
        "historyP2": "We have established mosques, educational institutions like the MIA Institute of Knowledge, and numerous community support programs over the years, reflecting our commitment to serving the evolving needs of Muslims in Manitoba.",
        "visionMissionTitle": "Vision & Mission",
        "visionTitle": "Our Vision",
        "visionText": "To be a leading Islamic organization, recognized for excellence in service, education, and outreach, contributing positively to the multicultural fabric of Manitoba and empowering Muslims to practice their faith and achieve their full potential.",
        "missionTitle": "Our Mission",
        "missionText": "To foster a vibrant, inclusive, and spiritually enriched Muslim community in Manitoba, guided by the teachings of Islam. We aim to provide comprehensive religious, educational, and social services, while promoting understanding, cooperation, and positive engagement within the community and with the broader society.",
        "leadershipTitle": "Leadership & Governance",
        "leaderRole": "President / Imam",
        "leaderName": "[Leader's Name Placeholder]",
        "leaderTitle": "[Leader's Title/Credentials Placeholder]",
        "governanceText": "MIA is governed by an elected board and supported by dedicated staff and volunteers. We adhere to principles of transparency and accountability in our operations.",
        "boardMembers": "Board Members",
        "governanceDocs": "Governance Docs",
        "volunteerTitle": "Volunteer Committees & Opportunities",
        "volunteerText": "Volunteers are the backbone of MIA. We have several active Volunteer Committees dedicated to various aspects of our work. We encourage community members to get involved and contribute their time and skills.",
        "getInvolved": "Get Involved",

        // Services Page
        "servicesPageTitle": "Community Services",
        "servicesIntro": "MIA is committed to providing a wide range of services to support the diverse needs of the Muslim community in Manitoba, fostering well-being and mutual support.",
        "janazahTitle": "Funeral Services (Janazah)",
        "janazahDesc": "We provide support and guidance for funeral arrangements according to Islamic traditions. Our team assists families during their time of need with compassion and care.",
        "marriageTitle": "Marriage Services",
        "marriageDesc": "MIA offers services related to Islamic marriage contracts (Nikah), including officiating ceremonies and providing pre-marital counseling.",
        "detailsBooking": "Details & Booking",
        "mentalHealthTitle": "Mental Health & Wellness",
        "mentalHealthDesc": "Confidential counselling services and resources to support individuals and families facing challenges, provided with cultural sensitivity.",
        "resourcesContact": "Resources & Contact",
        "takafulTitle": "Financial Assistance (Takaful)",
        "takafulDesc": "Through our Takaful program, we provide financial assistance to community members facing hardship, based on mutual support and Islamic charity.",
        "applyCriteria": "Apply / Criteria",
        "newMuslimsTitle": "New Muslim Support",
        "newMuslimsDesc": "Dedicated support and resources for individuals new to Islam, helping them integrate into the community and learn about their faith.",
        "getSupport": "Get Support",
        "outreachTitle": "Outreach Programs",
        "outreachDesc": "MIA actively engages in outreach programs to build bridges with the wider community, promote interfaith dialogue, and share information about Islam.",
        "ourPrograms": "Our Programs",
        "zakatSadaqahTitle": "Zakat & Sadaqah",
        "zakatSadaqahDesc": "We facilitate the collection and distribution of Zakat and Sadaqah according to Islamic guidelines, ensuring contributions reach those in need.",
        "donateInfo": "Donate / Info",
        "facilityRentalTitle": "Facility Rental",
        "facilityRentalDesc": "Our facilities, including halls and meeting rooms, are available for rent for community events and functions.",
        "bookingInfo": "Booking Information",

        // Religion Page
        "religionPageTitle": "Religious Services & Information",
        "prayerTimingsIntro": "Accurate prayer timings are crucial for daily worship. Find today's timings below and access the full monthly calendar.",
        "viewMonthlyCalendar": "View Monthly Calendar",
        "fcnaCalendarInfo": "FCNA Calendar Info",
        "jumuahTitle": "Friday Prayer (Jumuah)",
        "jumuahDesc": "Join us for the congregational Friday prayers. Sermons (Khutbahs) are delivered by knowledgeable speakers at multiple locations.",
        "khutbahSchedule": "Khutbah Schedule",
        "ramadanTitle": "Ramadan Information",
        "ramadanDesc": "During the blessed month of Ramadan, MIA organizes special prayers (Taraweeh), community Iftars, and other programs. Find relevant schedules and information here.",
        "ramadanPrograms": "Ramadan Programs",
        "fiqhCommitteeTitle": "MIA Fiqh Committee",
        "fiqhCommitteeDesc": "The MIA Fiqh Committee provides guidance on matters of Islamic jurisprudence relevant to the local community. Access rulings or submit inquiries.",
        "learnMoreContact": "Learn More / Contact",
        "askImamTitle": "Ask an Imam",
        "askImamDesc": "Have a question about religious matters? Our qualified Imams are available to provide guidance and clarification based on Islamic teachings.",
        "submitQuestion": "Submit Question",
        "zakatInfoTitle": "Zakat Information",
        "zakatInfoDesc": "Learn about the obligation of Zakat and how MIA facilitates its collection and distribution to eligible recipients within the community.",
        "zakatDetails": "Zakat Details",
        "affiliatedMosquesTitle": "Affiliated Mosques",
        "affiliatedMosquesDesc": "Find information about mosques affiliated with or supported by MIA, including locations and contact details.",
        "mosqueDirectory": "Mosque Directory",

        // Education Page
        "educationPageTitle": "Education Programs & Resources",
        "miaInstituteTitle": "MIA Institute of Knowledge",
        "miaInstituteIntro": "The MIA Institute of Knowledge is our dedicated educational institution providing quality Islamic and academic education from Kindergarten to Grade 9.",
        "miaInstituteDesc": "We strive to nurture well-rounded individuals grounded in faith and equipped for success. Learn more about our school, its programs, curriculum, admissions process, and dedicated staff.",
        "schoolWebsite": "School Website",
        "admissionsInfo": "Admissions Info",
        "otherProgramsTitle": "Other Educational Programs",
        "regularProgramsTitle": "Regular Programs",
        "regularProgramsDesc": "Beyond the full-time school, MIA offers various regular educational programs including weekend classes, evening lectures, and workshops on Islamic studies, Quranic learning, and Arabic language.",
        "viewSchedule": "View Schedule",
        "islamicStudiesTitle": "Islamic Studies Program",
        "islamicStudiesDesc": "Specific Islamic studies programs catering to adults and youth seeking deeper knowledge of their faith, covering topics like Tafsir, Hadith, Fiqh, and Seerah.",
        "programDetails": "Program Details",
        "libraryTitle": "Kids Library & Resources",
        "libraryDesc": "Encouraging reading and learning among children with our Kids Library and access to resources like Muslim Kids TV. We also facilitate requests for Islamic books for libraries.",
        "libraryInfo": "Library Info",
        "dawahTitle": "Sharing Knowledge (Dawah)",
        "dawahDesc": "Resources and initiatives aimed at sharing the message of Islam, including materials like \"Share the Prophet’s Message\" and the \"Manitoba Muslims\" book.",
        "orderResources": "Order Resources",
        "islamophobiaTitle": "Addressing Islamophobia",
        "islamophobiaDesc": "MIA provides resources and support related to understanding and addressing Islamophobia, promoting awareness and positive dialogue.",
        "islamophobiaResources": "Resources & Reporting",

        // Donate Page
        "donatePageTitle": "Support MIA",
        "donateIntro": "Your contributions are vital to sustaining the activities and services provided by the Manitoba Islamic Association. Help us continue our work in serving the community, providing education, supporting those in need, and maintaining our facilities. All donations are greatly appreciated and used responsibly.",
        "donationOptionsTitle": "Donation Options",
        "oneTimeDonationTitle": "One-Time Donation",
        "oneTimeDonationDesc": "Make a single contribution to support MIA's general operations or specific projects.",
        "donateNowOneTime": "Donate Now (One-Time)",
        "paymentGatewayPlaceholder": "Placeholder: Links to secure payment gateway.",
        "monthlyDonationTitle": "Monthly Donation",
        "monthlyDonationDesc": "Set up a recurring monthly donation to provide ongoing support for MIA's programs and services.",
        "donateMonthly": "Donate Monthly",
        "zakatDonationsTitle": "Zakat Donations",
        "zakatDonationsDesc": "You can fulfill your Zakat obligation through MIA. We ensure that Zakat funds are collected and distributed according to Islamic principles to eligible recipients within the local community.",
        "donateZakatHere": "Donate Zakat Here",
        "zakatCalculator": "Zakat Calculator",
        "distributionPolicy": "Distribution Policy",
        "specifyZakatNote": "Please specify 'Zakat' when making your donation if applicable.",
        "otherWaysTitle": "Other Ways to Give",
        "sadaqahJariyahTitle": "Sadaqah Jariyah",
        "sadaqahJariyahDesc": "Contribute to ongoing charity projects that provide continuous benefit, such as supporting infrastructure or educational programs.",
        "specificProjectsTitle": "Specific Projects",
        "specificProjectsDesc": "Support specific initiatives like mosque expansion, school development, or community outreach programs.",
        "viewProjects": "View Projects",
        "inKindDonationsTitle": "In-Kind Donations",
        "inKindDonationsDesc": "Contribute goods or services that can benefit MIA's operations or programs. Please contact us for details.",
        "miaWakfTitle": "MIA Wakf Foundation",
        "miaWakfDesc": "Support the long-term sustainability of MIA through contributions to the MIA Wakf Foundation endowment fund.",
        "wakfFoundation": "Wakf Foundation",
        "taxReceiptsTitle": "Tax Receipts",
        "taxReceiptsDesc": "MIA is a registered charity (Charity Registration Number: [Placeholder]). Tax receipts will be issued for eligible donations according to CRA guidelines. Please ensure you provide accurate contact information when donating."
    },
    fr: {
        // Nav & General
        "home": "Accueil",
        "about": "À Propos",
        "services": "Services",
        "religion": "Religion",
        "education": "Éducation",
        "donate": "Donner",
        "learnMore": "En Savoir Plus",
        "readMore": "Lire la Suite",
        "contactUs": "Contactez-Nous",
        "viewDetails": "Voir les Détails",
        "submit": "Soumettre",
        "officeHours": "Heures de Bureau : Lun-Ven, 9h - 17h",
        "copyrightFooter": "Copyright © 2024 Association Islamique du Manitoba. Tous Droits Réservés.",
        "quickLinksFooter": "Liens Rapides",
        "contactUsFooter": "Contactez-Nous",
        "aboutMIAFooter": "L'Association Islamique du Manitoba (MIA) se consacre à servir la communauté musulmane diversifiée du Manitoba par le biais de conseils religieux, d'éducation, de services sociaux et de développement communautaire.",

        // Index Page
        "welcomeTitle": "Bienvenue à l'Association Islamique du Manitoba",
        "welcomeSubtitle": "Servir la communauté musulmane du Manitoba par la foi, l'éducation et le service.",
        "learnMoreAboutUs": "En Savoir Plus Sur Nous",
        "ourServices": "Nos Services",
        "prayerTimingsTitle": "Horaires des Prières",
        "prayerDate": "4 mai 2025 / 6 Dhū al-Qaʻda 1446",
        "prayer": "Prière",
        "athan": "Athan",
        "iqamah": "Iqamah",
        "fajr": "Fajr",
        "sunrise": "Lever du Soleil",
        "zuhr": "Zuhr",
        "asr": "Asr",
        "maghrib": "Maghrib",
        "isha": "Isha",
        "jumuahTimings": "Jumuah : 13h45 | 15h45",
        "viewMonthlyTimings": "Voir les Horaires Mensuels",
        "quickLinksTitle": "Liens Rapides",
        "qlEvents": "Événements",
        "qlMiaInstitute": "Institut MIA",
        "qlEducation": "Éducation",
        "qlFinancialAssistance": "Aide Financière",
        "qlMiaWakf": "Wakf MIA",
        "qlNewMuslims": "Nouveaux Musulmans",
        "qlMentalHealth": "Santé Mentale",
        "qlMemberPortal": "Portail Membre",
        "qlVolunteer": "Bénévolat",
        "qlFuneralServices": "Services Funéraires",
        "newsTitle": "Dernières Nouvelles et Annonces",
        "news1Title": "Iftar Communautaire Samedi Prochain",
        "news1Date": "3 mai 2025",
        "news1Desc": "Rejoignez-nous pour un rassemblement communautaire et rompez votre jeûne ensemble. Tous sont les bienvenus !",
        "news2Title": "Inscriptions Ouvertes à l'École MIA",
        "news2Date": "1 mai 2025",
        "news2Desc": "Les inscriptions pour la prochaine année scolaire à l'Institut du Savoir MIA sont maintenant ouvertes. Sécurisez la place de votre enfant.",
        "news3Title": "Appel aux Bénévoles : Festival de l'Aïd",
        "news3Date": "28 avril 2025",
        "news3Desc": "Nous avons besoin de bénévoles pour contribuer au succès de notre prochain festival de l'Aïd. Inscrivez-vous dès aujourd'hui !",
        "volunteer": "Devenir Bénévole",
        "supportTitle": "Soutenez Votre Centre Communautaire",
        "supportText": "Vos dons généreux nous aident à entretenir nos installations, à gérer des programmes essentiels et à servir la communauté.",
        "donateNow": "Donner Maintenant",

        // About Page
        "historyTitle": "Notre Histoire",
        "historyP1": "L'Association Islamique du Manitoba (MIA) trouve ses origines à la fin des années cinquante et au début des années soixante du 20e siècle, lorsque les immigrants musulmans au Manitoba se sont réunis pour prier, apprendre et socialiser. Fondée officiellement en [Année - Placeholder], la MIA est passée d'un petit groupe de pionniers à une organisation centrale pour la communauté musulmane diversifiée de la province.",
        "historyP2": "Nous avons établi des mosquées, des institutions éducatives comme l'Institut du Savoir MIA, et de nombreux programmes de soutien communautaire au fil des ans, reflétant notre engagement à répondre aux besoins changeants des musulmans au Manitoba.",
        "visionMissionTitle": "Vision et Mission",
        "visionTitle": "Notre Vision",
        "visionText": "Être une organisation islamique de premier plan, reconnue pour l'excellence de ses services, de son éducation et de sa sensibilisation, contribuant positivement au tissu multiculturel du Manitoba et permettant aux musulmans de pratiquer leur foi et d'atteindre leur plein potentiel.",
        "missionTitle": "Notre Mission",
        "missionText": "Favoriser une communauté musulmane dynamique, inclusive et spirituellement enrichie au Manitoba, guidée par les enseignements de l'Islam. Nous visons à fournir des services religieux, éducatifs et sociaux complets, tout en promouvant la compréhension, la coopération et un engagement positif au sein de la communauté et avec la société élargie.",
        "leadershipTitle": "Direction et Gouvernance",
        "leaderRole": "Président / Imam",
        "leaderName": "[Nom du Dirigeant - Placeholder]",
        "leaderTitle": "[Titre/Qualifications du Dirigeant - Placeholder]",
        "governanceText": "La MIA est dirigée par un conseil élu et soutenue par du personnel dévoué et des bénévoles. Nous adhérons aux principes de transparence et de responsabilité dans nos opérations.",
        "boardMembers": "Membres du Conseil",
        "governanceDocs": "Docs de Gouvernance",
        "volunteerTitle": "Comités de Bénévoles et Opportunités",
        "volunteerText": "Les bénévoles sont l'épine dorsale de la MIA. Nous avons plusieurs comités de bénévoles actifs dédiés à divers aspects de notre travail. Nous encourageons les membres de la communauté à s'impliquer et à contribuer leur temps et leurs compétences.",
        "getInvolved": "S'impliquer",

        // Services Page
        "servicesPageTitle": "Services Communautaires",
        "servicesIntro": "La MIA s'engage à fournir une large gamme de services pour répondre aux divers besoins de la communauté musulmane au Manitoba, favorisant le bien-être et le soutien mutuel.",
        "janazahTitle": "Services Funéraires (Janazah)",
        "janazahDesc": "Nous fournissons soutien et conseils pour l'organisation des funérailles selon les traditions islamiques. Notre équipe assiste les familles dans leur moment de besoin avec compassion et soin.",
        "marriageTitle": "Services de Mariage",
        "marriageDesc": "La MIA offre des services liés aux contrats de mariage islamiques (Nikah), y compris l'officialisation des cérémonies et le conseil prénuptial.",
        "detailsBooking": "Détails et Réservation",
        "mentalHealthTitle": "Santé Mentale et Bien-être",
        "mentalHealthDesc": "Services de conseil confidentiels et ressources pour soutenir les individus et les familles confrontés à des défis, fournis avec sensibilité culturelle.",
        "resourcesContact": "Ressources et Contact",
        "takafulTitle": "Aide Financière (Takaful)",
        "takafulDesc": "Grâce à notre programme Takaful, nous fournissons une aide financière aux membres de la communauté confrontés à des difficultés, basée sur le soutien mutuel et la charité islamique.",
        "applyCriteria": "Postuler / Critères",
        "newMuslimsTitle": "Soutien aux Nouveaux Musulmans",
        "newMuslimsDesc": "Soutien et ressources dédiés aux personnes nouvelles dans l'Islam, les aidant à s'intégrer dans la communauté et à apprendre leur foi.",
        "getSupport": "Obtenir du Soutien",
        "outreachTitle": "Programmes de Sensibilisation",
        "outreachDesc": "La MIA s'engage activement dans des programmes de sensibilisation pour construire des ponts avec la communauté élargie, promouvoir le dialogue interreligieux et partager des informations sur l'Islam.",
        "ourPrograms": "Nos Programmes",
        "zakatSadaqahTitle": "Zakat et Sadaqah",
        "zakatSadaqahDesc": "Nous facilitons la collecte et la distribution de la Zakat et de la Sadaqah selon les directives islamiques, en veillant à ce que les contributions parviennent à ceux qui en ont besoin.",
        "donateInfo": "Donner / Info",
        "facilityRentalTitle": "Location d'Installations",
        "facilityRentalDesc": "Nos installations, y compris les salles et les salles de réunion, sont disponibles à la location pour des événements et fonctions communautaires.",
        "bookingInfo": "Informations de Réservation",

        // Religion Page
        "religionPageTitle": "Services et Informations Religieux",
        "prayerTimingsIntro": "Des horaires de prière précis sont cruciaux pour le culte quotidien. Trouvez les horaires d'aujourd'hui ci-dessous et accédez au calendrier mensuel complet.",
        "viewMonthlyCalendar": "Voir le Calendrier Mensuel",
        "fcnaCalendarInfo": "Info Calendrier FCNA",
        "jumuahTitle": "Prière du Vendredi (Jumuah)",
        "jumuahDesc": "Rejoignez-nous pour les prières collectives du vendredi. Les sermons (Khutbahs) sont prononcés par des orateurs compétents dans plusieurs endroits.",
        "khutbahSchedule": "Horaire des Khutbahs",
        "ramadanTitle": "Informations sur le Ramadan",
        "ramadanDesc": "Pendant le mois béni du Ramadan, la MIA organise des prières spéciales (Taraweeh), des Iftars communautaires et d'autres programmes. Trouvez les horaires et informations pertinents ici.",
        "ramadanPrograms": "Programmes du Ramadan",
        "fiqhCommitteeTitle": "Comité Fiqh de la MIA",
        "fiqhCommitteeDesc": "Le Comité Fiqh de la MIA fournit des conseils sur les questions de jurisprudence islamique pertinentes pour la communauté locale. Accédez aux décisions ou soumettez des demandes.",
        "learnMoreContact": "En Savoir Plus / Contact",
        "askImamTitle": "Demandez à un Imam",
        "askImamDesc": "Vous avez une question sur des sujets religieux ? Nos Imams qualifiés sont disponibles pour fournir des conseils et des éclaircissements basés sur les enseignements islamiques.",
        "submitQuestion": "Soumettre une Question",
        "zakatInfoTitle": "Informations sur la Zakat",
        "zakatInfoDesc": "Apprenez-en davantage sur l'obligation de la Zakat et comment la MIA facilite sa collecte et sa distribution aux bénéficiaires éligibles au sein de la communauté.",
        "zakatDetails": "Détails sur la Zakat",
        "affiliatedMosquesTitle": "Mosquées Affiliées",
        "affiliatedMosquesDesc": "Trouvez des informations sur les mosquées affiliées ou soutenues par la MIA, y compris les emplacements et les coordonnées.",
        "mosqueDirectory": "Annuaire des Mosquées",

        // Education Page
        "educationPageTitle": "Programmes et Ressources Éducatifs",
        "miaInstituteTitle": "Institut du Savoir MIA",
        "miaInstituteIntro": "L'Institut du Savoir MIA est notre institution éducative dédiée offrant une éducation islamique et académique de qualité de la maternelle à la 9e année.",
        "miaInstituteDesc": "Nous nous efforçons de former des individus équilibrés, ancrés dans la foi et équipés pour réussir. Apprenez-en davantage sur notre école, ses programmes, son curriculum, son processus d'admission et son personnel dévoué.",
        "schoolWebsite": "Site Web de l'École",
        "admissionsInfo": "Infos Admissions",
        "otherProgramsTitle": "Autres Programmes Éducatifs",
        "regularProgramsTitle": "Programmes Réguliers",
        "regularProgramsDesc": "Au-delà de l'école à temps plein, la MIA propose divers programmes éducatifs réguliers, notamment des cours le week-end, des conférences en soirée et des ateliers sur les études islamiques, l'apprentissage du Coran et la langue arabe.",
        "viewSchedule": "Voir l'Horaire",
        "islamicStudiesTitle": "Programme d'Études Islamiques",
        "islamicStudiesDesc": "Programmes spécifiques d'études islamiques destinés aux adultes et aux jeunes cherchant une connaissance plus approfondie de leur foi, couvrant des sujets tels que le Tafsir, le Hadith, le Fiqh et la Seerah.",
        "programDetails": "Détails du Programme",
        "libraryTitle": "Bibliothèque Enfants et Ressources",
        "libraryDesc": "Encourager la lecture et l'apprentissage chez les enfants avec notre Bibliothèque Enfants et l'accès à des ressources comme Muslim Kids TV. Nous facilitons également les demandes de livres islamiques pour les bibliothèques.",
        "libraryInfo": "Info Bibliothèque",
        "dawahTitle": "Partage des Connaissances (Dawah)",
        "dawahDesc": "Ressources et initiatives visant à partager le message de l'Islam, y compris des matériaux comme \"Partagez le Message du Prophète\" et le livre \"Manitoba Muslims\".",
        "orderResources": "Commander des Ressources",
        "islamophobiaTitle": "Lutte contre l'Islamophobie",
        "islamophobiaDesc": "La MIA fournit des ressources et un soutien liés à la compréhension et à la lutte contre l'islamophobie, promouvant la sensibilisation et un dialogue positif.",
        "islamophobiaResources": "Ressources et Signalement",

        // Donate Page
        "donatePageTitle": "Soutenir la MIA",
        "donateIntro": "Vos contributions sont vitales pour soutenir les activités et les services fournis par l'Association Islamique du Manitoba. Aidez-nous à poursuivre notre travail au service de la communauté, en fournissant une éducation, en soutenant ceux qui sont dans le besoin et en entretenant nos installations. Tous les dons sont grandement appréciés et utilisés de manière responsable.",
        "donationOptionsTitle": "Options de Don",
        "oneTimeDonationTitle": "Don Unique",
        "oneTimeDonationDesc": "Faites une contribution unique pour soutenir les opérations générales de la MIA ou des projets spécifiques.",
        "donateNowOneTime": "Donner Maintenant (Unique)",
        "paymentGatewayPlaceholder": "Placeholder : Liens vers une passerelle de paiement sécurisée.",
        "monthlyDonationTitle": "Don Mensuel",
        "monthlyDonationDesc": "Mettez en place un don mensuel récurrent pour fournir un soutien continu aux programmes et services de la MIA.",
        "donateMonthly": "Donner Mensuellement",
        "zakatDonationsTitle": "Dons de Zakat",
        "zakatDonationsDesc": "Vous pouvez remplir votre obligation de Zakat par l'intermédiaire de la MIA. Nous veillons à ce que les fonds de la Zakat soient collectés et distribués selon les principes islamiques aux bénéficiaires éligibles au sein de la communauté locale.",
        "donateZakatHere": "Donner la Zakat Ici",
        "zakatCalculator": "Calculateur de Zakat",
        "distributionPolicy": "Politique de Distribution",
        "specifyZakatNote": "Veuillez spécifier 'Zakat' lors de votre don si applicable.",
        "otherWaysTitle": "Autres Façons de Donner",
        "sadaqahJariyahTitle": "Sadaqah Jariyah",
        "sadaqahJariyahDesc": "Contribuez à des projets caritatifs continus qui offrent un bénéfice continu, tels que le soutien aux infrastructures ou aux programmes éducatifs.",
        "specificProjectsTitle": "Projets Spécifiques",
        "specificProjectsDesc": "Soutenez des initiatives spécifiques comme l'agrandissement de la mosquée, le développement de l'école ou les programmes de sensibilisation communautaire.",
        "viewProjects": "Voir les Projets",
        "inKindDonationsTitle": "Dons en Nature",
        "inKindDonationsDesc": "Contribuez des biens ou des services qui peuvent bénéficier aux opérations ou aux programmes de la MIA. Veuillez nous contacter pour plus de détails.",
        "miaWakfTitle": "Fondation Wakf MIA",
        "miaWakfDesc": "Soutenez la durabilité à long terme de la MIA par des contributions au fonds de dotation de la Fondation Wakf MIA.",
        "wakfFoundation": "Fondation Wakf",
        "taxReceiptsTitle": "Reçus Fiscaux",
        "taxReceiptsDesc": "La MIA est un organisme de bienfaisance enregistré (Numéro d'enregistrement d'organisme de bienfaisance : [Placeholder]). Des reçus fiscaux seront émis pour les dons éligibles conformément aux directives de l'ARC. Veuillez vous assurer de fournir des informations de contact exactes lors de votre don."
    },
    ar: {
        // Nav & General
        "home": "الرئيسية",
        "about": "من نحن",
        "services": "الخدمات",
        "religion": "الدين",
        "education": "التعليم",
        "donate": "تبرع",
        "learnMore": "اعرف المزيد",
        "readMore": "اقرأ المزيد",
        "contactUs": "اتصل بنا",
        "viewDetails": "عرض التفاصيل",
        "submit": "إرسال",
        "officeHours": "ساعات العمل: الاثنين - الجمعة، 9 صباحًا - 5 مساءً",
        "copyrightFooter": "حقوق النشر © 2024 الجمعية الإسلامية في مانيتوبا. جميع الحقوق محفوظة.",
        "quickLinksFooter": "روابط سريعة",
        "contactUsFooter": "اتصل بنا",
        "aboutMIAFooter": "تكرس الجمعية الإسلامية في مانيتوبا (MIA) جهودها لخدمة المجتمع المسلم المتنوع في مانيتوبا من خلال التوجيه الديني والتعليم والخدمات الاجتماعية وبناء المجتمع.",

        // Index Page
        "welcomeTitle": "مرحبًا بكم في الجمعية الإسلامية في مانيتوبا",
        "welcomeSubtitle": "خدمة المجتمع المسلم في مانيتوبا من خلال الإيمان والتعليم والخدمة.",
        "learnMoreAboutUs": "اعرف المزيد عنا",
        "ourServices": "خدماتنا",
        "prayerTimingsTitle": "أوقات الصلاة",
        "prayerDate": "4 مايو 2025 / 6 ذو القعدة 1446",
        "prayer": "الصلاة",
        "athan": "الأذان",
        "iqamah": "الإقامة",
        "fajr": "الفجر",
        "sunrise": "الشروق",
        "zuhr": "الظهر",
        "asr": "العصر",
        "maghrib": "المغرب",
        "isha": "العشاء",
        "jumuahTimings": "الجمعة: 1:45 مساءً | 3:45 مساءً",
        "viewMonthlyTimings": "عرض الأوقات الشهرية",
        "quickLinksTitle": "روابط سريعة",
        "qlEvents": "الفعاليات",
        "qlMiaInstitute": "معهد MIA",
        "qlEducation": "التعليم",
        "qlFinancialAssistance": "المساعدة المالية",
        "qlMiaWakf": "وقف MIA",
        "qlNewMuslims": "المسلمون الجدد",
        "qlMentalHealth": "الصحة النفسية",
        "qlMemberPortal": "بوابة الأعضاء",
        "qlVolunteer": "التطوع",
        "qlFuneralServices": "خدمات الجنازة",
        "newsTitle": "آخر الأخبار والإعلانات",
        "news1Title": "إفطار جماعي السبت القادم",
        "news1Date": "3 مايو 2025",
        "news1Desc": "انضم إلينا في تجمع مجتمعي وافطر معنا. الجميع مرحب بهم!",
        "news2Title": "فتح باب التسجيل في مدرسة MIA",
        "news2Date": "1 مايو 2025",
        "news2Desc": "التسجيل للعام الدراسي القادم في معهد MIA للمعرفة مفتوح الآن. احجز مكان طفلك.",
        "news3Title": "دعوة للتطوع: مهرجان العيد",
        "news3Date": "28 أبريل 2025",
        "news3Desc": "نحتاج إلى متطوعين للمساعدة في إنجاح مهرجان العيد القادم. سجل اليوم!",
        "volunteer": "تطوع",
        "supportTitle": "ادعم مركز مجتمعك",
        "supportText": "تبرعاتكم السخية تساعدنا في الحفاظ على منشآتنا وتشغيل البرامج الأساسية وخدمة المجتمع.",
        "donateNow": "تبرع الآن",

        // About Page
        "historyTitle": "تاريخنا",
        "historyP1": "تعود جذور الجمعية الإسلامية في مانيتوبا (MIA) إلى أواخر الخمسينيات وأوائل الستينيات من القرن العشرين، عندما اجتمع المهاجرون المسلمون إلى مانيتوبا للعبادة والتعلم والتواصل الاجتماعي. تأسست MIA رسميًا في [السنة - Placeholder]، ونمت من مجموعة صغيرة من الرواد لتصبح منظمة مركزية للمجتمع المسلم المتنوع في المقاطعة.",
        "historyP2": "لقد أنشأنا مساجد ومؤسسات تعليمية مثل معهد MIA للمعرفة والعديد من برامج دعم المجتمع على مر السنين، مما يعكس التزامنا بتلبية الاحتياجات المتطورة للمسلمين في مانيتوبا.",
        "visionMissionTitle": "الرؤية والرسالة",
        "visionTitle": "رؤيتنا",
        "visionText": "أن نكون منظمة إسلامية رائدة، معترف بها للتميز في الخدمة والتعليم والتوعية، والمساهمة بشكل إيجابي في النسيج متعدد الثقافات في مانيتوبا وتمكين المسلمين من ممارسة دينهم وتحقيق إمكاناتهم الكاملة.",
        "missionTitle": "رسالتنا",
        "missionText": "تعزيز مجتمع مسلم نابض بالحياة وشامل ومثرى روحياً في مانيتوبا، مسترشدين بتعاليم الإسلام. نهدف إلى تقديم خدمات دينية وتعليمية واجتماعية شاملة، مع تعزيز التفاهم والتعاون والمشاركة الإيجابية داخل المجتمع ومع المجتمع الأوسع.",
        "leadershipTitle": "القيادة والحوكمة",
        "leaderRole": "الرئيس / الإمام",
        "leaderName": "[اسم القائد - Placeholder]",
        "leaderTitle": "[لقب/مؤهلات القائد - Placeholder]",
        "governanceText": "تُدار MIA من قبل مجلس منتخب وتدعمها طاقم عمل متفانٍ ومتطوعون. نلتزم بمبادئ الشفافية والمساءلة في عملياتنا.",
        "boardMembers": "أعضاء المجلس",
        "governanceDocs": "وثائق الحوكمة",
        "volunteerTitle": "لجان المتطوعين والفرص",
        "volunteerText": "المتطوعون هم العمود الفقري لـ MIA. لدينا العديد من لجان المتطوعين النشطة المكرسة لمختلف جوانب عملنا. نشجع أفراد المجتمع على المشاركة والمساهمة بوقتهم ومهاراتهم.",
        "getInvolved": "شارك",

        // Services Page
        "servicesPageTitle": "الخدمات المجتمعية",
        "servicesIntro": "تلتزم MIA بتقديم مجموعة واسعة من الخدمات لدعم الاحتياجات المتنوعة للمجتمع المسلم في مانيتوبا، وتعزيز الرفاهية والدعم المتبادل.",
        "janazahTitle": "خدمات الجنازة",
        "janazahDesc": "نقدم الدعم والتوجيه لترتيبات الجنازة وفقًا للتقاليد الإسلامية. يساعد فريقنا العائلات في وقت حاجتهم بالرحمة والرعاية.",
        "marriageTitle": "خدمات الزواج",
        "marriageDesc": "تقدم MIA خدمات تتعلق بعقود الزواج الإسلامية (النكاح)، بما في ذلك إقامة المراسم وتقديم المشورة قبل الزواج.",
        "detailsBooking": "التفاصيل والحجز",
        "mentalHealthTitle": "الصحة النفسية والعافية",
        "mentalHealthDesc": "خدمات استشارية سرية وموارد لدعم الأفراد والأسر الذين يواجهون تحديات، مقدمة بحساسية ثقافية.",
        "resourcesContact": "الموارد والاتصال",
        "takafulTitle": "المساعدة المالية (تكافل)",
        "takafulDesc": "من خلال برنامج تكافل الخاص بنا، نقدم المساعدة المالية لأفراد المجتمع الذين يواجهون صعوبات، بناءً على الدعم المتبادل والصدقة الإسلامية.",
        "applyCriteria": "التقديم / المعايير",
        "newMuslimsTitle": "دعم المسلمين الجدد",
        "newMuslimsDesc": "دعم وموارد مخصصة للأفراد الجدد في الإسلام، لمساعدتهم على الاندماج في المجتمع وتعلم دينهم.",
        "getSupport": "احصل على الدعم",
        "outreachTitle": "برامج التوعية",
        "outreachDesc": "تشارك MIA بنشاط في برامج التوعية لبناء الجسور مع المجتمع الأوسع، وتعزيز الحوار بين الأديان، ومشاركة المعلومات حول الإسلام.",
        "ourPrograms": "برامجنا",
        "zakatSadaqahTitle": "الزكاة والصدقة",
        "zakatSadaqahDesc": "نسهل جمع وتوزيع الزكاة والصدقة وفقًا للمبادئ التوجيهية الإسلامية، مما يضمن وصول المساهمات إلى المحتاجين.",
        "donateInfo": "تبرع / معلومات",
        "facilityRentalTitle": "تأجير المرافق",
        "facilityRentalDesc": "مرافقنا، بما في ذلك القاعات وغرف الاجتماعات، متاحة للإيجار للمناسبات والوظائف المجتمعية.",
        "bookingInfo": "معلومات الحجز",

        // Religion Page
        "religionPageTitle": "الخدمات والمعلومات الدينية",
        "prayerTimingsIntro": "أوقات الصلاة الدقيقة ضرورية للعبادة اليومية. ابحث عن أوقات اليوم أدناه وقم بالوصول إلى التقويم الشهري الكامل.",
        "viewMonthlyCalendar": "عرض التقويم الشهري",
        "fcnaCalendarInfo": "معلومات تقويم FCNA",
        "jumuahTitle": "صلاة الجمعة",
        "jumuahDesc": "انضم إلينا في صلاة الجمعة الجماعية. يلقي الخطب خطباء مطلعون في مواقع متعددة.",
        "khutbahSchedule": "جدول الخطب",
        "ramadanTitle": "معلومات رمضان",
        "ramadanDesc": "خلال شهر رمضان المبارك، تنظم MIA صلوات خاصة (التراويح)، وإفطارات جماعية، وبرامج أخرى. ابحث عن الجداول والمعلومات ذات الصلة هنا.",
        "ramadanPrograms": "برامج رمضان",
        "fiqhCommitteeTitle": "لجنة الفقه في MIA",
        "fiqhCommitteeDesc": "تقدم لجنة الفقه في MIA التوجيه بشأن مسائل الفقه الإسلامي ذات الصلة بالمجتمع المحلي. يمكنك الوصول إلى الأحكام أو تقديم الاستفسارات.",
        "learnMoreContact": "اعرف المزيد / اتصل",
        "askImamTitle": "اسأل إمامًا",
        "askImamDesc": "هل لديك سؤال حول الأمور الدينية؟ أئمتنا المؤهلون متاحون لتقديم التوجيه والتوضيح بناءً على التعاليم الإسلامية.",
        "submitQuestion": "إرسال سؤال",
        "zakatInfoTitle": "معلومات الزكاة",
        "zakatInfoDesc": "تعرف على واجب الزكاة وكيف تسهل MIA جمعها وتوزيعها على المستحقين المؤهلين داخل المجتمع.",
        "zakatDetails": "تفاصيل الزكاة",
        "affiliatedMosquesTitle": "المساجد التابعة",
        "affiliatedMosquesDesc": "ابحث عن معلومات حول المساجد التابعة لـ MIA أو المدعومة منها، بما في ذلك المواقع وتفاصيل الاتصال.",
        "mosqueDirectory": "دليل المساجد",

        // Education Page
        "educationPageTitle": "البرامج والموارد التعليمية",
        "miaInstituteTitle": "معهد MIA للمعرفة",
        "miaInstituteIntro": "معهد MIA للمعرفة هو مؤسستنا التعليمية المخصصة التي تقدم تعليمًا إسلاميًا وأكاديميًا عالي الجودة من رياض الأطفال حتى الصف التاسع.",
        "miaInstituteDesc": "نسعى جاهدين لتنشئة أفراد متكاملين راسخين في الإيمان ومجهزين للنجاح. تعرف على المزيد حول مدرستنا وبرامجها ومناهجها وعملية القبول والموظفين المتفانين.",
        "schoolWebsite": "موقع المدرسة",
        "admissionsInfo": "معلومات القبول",
        "otherProgramsTitle": "البرامج التعليمية الأخرى",
        "regularProgramsTitle": "البرامج المنتظمة",
        "regularProgramsDesc": "بالإضافة إلى المدرسة بدوام كامل، تقدم MIA برامج تعليمية منتظمة متنوعة بما في ذلك فصول نهاية الأسبوع والمحاضرات المسائية وورش العمل حول الدراسات الإسلامية وتعلم القرآن واللغة العربية.",
        "viewSchedule": "عرض الجدول الزمني",
        "islamicStudiesTitle": "برنامج الدراسات الإسلامية",
        "islamicStudiesDesc": "برامج دراسات إسلامية محددة تلبي احتياجات البالغين والشباب الذين يسعون إلى معرفة أعمق بدينهم، وتغطي موضوعات مثل التفسير والحديث والفقه والسيرة.",
        "programDetails": "تفاصيل البرنامج",
        "libraryTitle": "مكتبة الأطفال والموارد",
        "libraryDesc": "تشجيع القراءة والتعلم بين الأطفال من خلال مكتبة الأطفال الخاصة بنا والوصول إلى موارد مثل Muslim Kids TV. كما نسهل طلبات الكتب الإسلامية للمكتبات.",
        "libraryInfo": "معلومات المكتبة",
        "dawahTitle": "مشاركة المعرفة (الدعوة)",
        "dawahDesc": "موارد ومبادرات تهدف إلى مشاركة رسالة الإسلام، بما في ذلك مواد مثل \"شارك رسالة النبي\" وكتاب \"مسلمو مانيتوبا\".",
        "orderResources": "طلب الموارد",
        "islamophobiaTitle": "التصدي للإسلاموفوبيا",
        "islamophobiaDesc": "توفر MIA الموارد والدعم المتعلق بفهم الإسلاموفوبيا والتصدي لها، وتعزيز الوعي والحوار الإيجابي.",
        "islamophobiaResources": "الموارد والإبلاغ",

        // Donate Page
        "donatePageTitle": "ادعم MIA",
        "donateIntro": "مساهماتكم حيوية لاستدامة الأنشطة والخدمات التي تقدمها الجمعية الإسلامية في مانيتوبا. ساعدونا على مواصلة عملنا في خدمة المجتمع، وتوفير التعليم، ودعم المحتاجين، وصيانة مرافقنا. جميع التبرعات محل تقدير كبير وتستخدم بمسؤولية.",
        "donationOptionsTitle": "خيارات التبرع",
        "oneTimeDonationTitle": "تبرع لمرة واحدة",
        "oneTimeDonationDesc": "قدم مساهمة لمرة واحدة لدعم العمليات العامة لـ MIA أو مشاريع محددة.",
        "donateNowOneTime": "تبرع الآن (مرة واحدة)",
        "paymentGatewayPlaceholder": "Placeholder: روابط لبوابة دفع آمنة.",
        "monthlyDonationTitle": "تبرع شهري",
        "monthlyDonationDesc": "قم بإعداد تبرع شهري متكرر لتقديم دعم مستمر لبرامج وخدمات MIA.",
        "donateMonthly": "تبرع شهريًا",
        "zakatDonationsTitle": "تبرعات الزكاة",
        "zakatDonationsDesc": "يمكنك أداء زكاتك من خلال MIA. نضمن جمع أموال الزكاة وتوزيعها وفقًا للمبادئ الإسلامية على المستحقين المؤهلين داخل المجتمع المحلي.",
        "donateZakatHere": "تبرع بالزكاة هنا",
        "zakatCalculator": "حاسبة الزكاة",
        "distributionPolicy": "سياسة التوزيع",
        "specifyZakatNote": "يرجى تحديد 'زكاة' عند التبرع إن أمكن.",
        "otherWaysTitle": "طرق أخرى للتبرع",
        "sadaqahJariyahTitle": "صدقة جارية",
        "sadaqahJariyahDesc": "ساهم في مشاريع خيرية مستمرة توفر فائدة مستمرة، مثل دعم البنية التحتية أو البرامج التعليمية.",
        "specificProjectsTitle": "مشاريع محددة",
        "specificProjectsDesc": "ادعم مبادرات محددة مثل توسعة المسجد أو تطوير المدرسة أو برامج التوعية المجتمعية.",
        "viewProjects": "عرض المشاريع",
        "inKindDonationsTitle": "تبرعات عينية",
        "inKindDonationsDesc": "ساهم بسلع أو خدمات يمكن أن تفيد عمليات أو برامج MIA. يرجى الاتصال بنا للحصول على التفاصيل.",
        "miaWakfTitle": "مؤسسة وقف MIA",
        "miaWakfDesc": "ادعم استدامة MIA على المدى الطويل من خلال المساهمات في صندوق وقف مؤسسة وقف MIA.",
        "wakfFoundation": "مؤسسة الوقف",
        "taxReceiptsTitle": "إيصالات الضرائب",
        "taxReceiptsDesc": "MIA هي مؤسسة خيرية مسجلة (رقم تسجيل المؤسسة الخيرية: [Placeholder]). سيتم إصدار إيصالات ضريبية للتبرعات المؤهلة وفقًا لإرشادات CRA. يرجى التأكد من تقديم معلومات اتصال دقيقة عند التبرع."
    }
};

let currentLang = localStorage.getItem('miaLang') || 'en';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('miaLang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    translatePage();
    updateActiveButton();
}

function translatePage() {
    document.querySelectorAll('[data-translate-key]').forEach(element => {
        const key = element.getAttribute('data-translate-key');
        if (translations[currentLang] && translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        } else {
            // Fallback or log error if translation missing
            // console.warn(`Translation key "${key}" not found for language "${currentLang}"`);
            // Optionally fallback to English
            if (translations['en'] && translations['en'][key]) {
                 element.textContent = translations['en'][key];
            } else {
                // Keep original text if English fallback also missing
                // console.error(`Fallback translation key "${key}" not found for English`);
            }
        }
    });
}

function updateActiveButton() {
    document.querySelectorAll('.language-btn').forEach(button => {
        if (button.getAttribute('data-lang') === currentLang) {
            button.classList.add('active');
        } else {
            button.classList.remove('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    // Set initial language based on localStorage or default
    setLanguage(currentLang);

    // Add event listeners to language buttons
    document.querySelectorAll('.language-btn').forEach(button => {
        button.addEventListener('click', () => {
            const lang = button.getAttribute('data-lang');
            setLanguage(lang);
        });
    });

    // Mobile Menu Toggle
    const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
    const mobileNav = document.querySelector('.mobile-nav');
    if (mobileMenuBtn && mobileNav) {
        mobileMenuBtn.addEventListener('click', () => {
            mobileNav.classList.toggle('active');
        });
    }

    // Scroll Animations
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('animate__animated', 'animate__fadeInUp');
                observer.unobserve(entry.target);
            }
        });
    }, { threshold: 0.1 });

    document.querySelectorAll('.animate-on-scroll').forEach(el => {
        observer.observe(el);
    });
});

